const EVENT_TYPES = [
    'STORAGE_WAS_TURN_ON',
    'STORAGE_WAS_TURN_OFF',
    'STORAGE_WAS_EMPTIED',
    'STORAGE_WAS_FILLED',
    'NEW_CIGARETTE_BUTT_STORED',
];

const eventTypes = {
    STORAGE_WAS_TURN_ON: 'STORAGE_WAS_TURN_ON',
    STORAGE_WAS_TURN_OFF: 'STORAGE_WAS_TURN_OFF',
    STORAGE_WAS_EMPTIED: 'STORAGE_WAS_EMPTIED',
    STORAGE_WAS_FILLED: 'STORAGE_WAS_FILLED',
    NEW_CIGARETTE_BUTT_STORED: 'NEW_CIGARETTE_BUTT_STORED',
}
module.exports = EVENT_TYPES;